config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "users#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :members do
    resources :broadcasts
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/broadcast.rb
class Broadcast < ApplicationRecord
  has_one_attached :post_image
  belongs_to :member
end

app/models/member.rb
class Member < ApplicationRecord
  has_many :broadcasts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/broadcasts_controllers.rb
class BroadcastsController < ApplicationController
  before_action :authorize, only: [:new, :create, :edit, :update, :destroy]
  # before_action :authenticate_member!

  def new
    @member = Member.find(params[:member_id])
    @broadcast = @member.broadcasts.new
    render :new
  end

  def create
    @member = Member.find(params[:member_id])
    @broadcast = @member.broadcasts.new(broadcast_params)
    if @broadcast.save
      redirect_to member_path(@member)
    else
      render :new
    end
  end

  def show
    @member = Member.find(params[:member_id])
    @broadcast = Broadcast.find(params[:id])
    render :show
  end

  def edit
    @member = Member.find(params[:member_id])
    @broadcast = Broadcast.find(params[:id])
    render :edit
  end

  def update
    @broadcast = Broadcast.find(params[:id])
    if @broadcast.update(broadcast_params)
      redirect_to member_path(@broadcast.member)
    else
      render :edit
    end
  end

  def destroy
    @broadcast = Broadcast.find(params[:id])
    @broadcast.destroy
    redirect_to member_path(@broadcast.member)
  end
  def broadcast_params
    params.require(:broadcast).permit(:description, :broadcast_image)
  end
end

app/controllers/members_controller.rb
require 'pry'

class MembersController < ApplicationController
  # before_action :authorize, only: [:new, :create, :edit, :update, :destroy]
# before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @members = Member.all
    # binding.pry
    render :index
  end

  def new
    @member = Member.new
    render :new
  end

  def create
    @member = Member.new(member_params)
    if @member.save
      flash[:notice] = "Member Created!"
      session[:member_id] = @member.id
      redirect_to members_path
    else
      flash[:alert] = "There was a problem making a member."
      redirect_to '/signup'
    end
  end

  def edit
    @member = Member.find(params[:id])
    render :edit
  end

  def show
    @member = Member.find(params[:id])
    render :show
  end

  def update
    @member = Member.find(params[:id])
    if @member.update(member_params)
      redirect_to members_path
    else
      render :edit
    end
  end

  def destroy
    @member = Member.find(params[:id])
    @member.destroy
    redirect_to members_path
  end

  private

  def member_params
    params.require(:member).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :authorize, only: [:edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @users = User.all
    render :index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "You've successfully signed up!"
      session[:user_id] = @user.id
      redirect_to "/"
    else
      flash[:alert] = "There was a problem signing up."
      redirect_to '/signup'
    end
  end

  def edit
    @user = User.find(params[:id])
    render :edit
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to users_path
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/broadcasts/edit.html.erb
<h2>Edit Broadcast</h2>
<%= render "layouts/broadcast_form" %>

app/views/broadcasts/index.html.erb
<h2>All Broadcasts</h2>

app/views/broadcasts/new.html.erb
<h2>New Broadcast</h2>
<%= render "layouts/broadcast_form" %>

app/views/broadcasts/show.html.erb
<h2>View Broadcast: </h2>

app/views/layouts/_broadcast_form.html.erb
<%= form_for @broadcast do |f| %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.label :post_image %>
  <%= f.file_field :post_image %>
  <%= f.submit  %>
<% end %>

app/views/layouts/_member_form.html.erb
<%= form_for @member do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit  %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flickrtwo</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <p class="navbar-text float-right">
    <a href="/">Home</a> |
    <%= link_to "Members", members_path %> <br>
    <% if user_signed_in? %>
    Logged in as <strong><%= current_user.email %></strong>.
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %> |
    <% else %>
    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %> |
    <% end %>

  </p>

  <h1>The site of awesome</h1>

  <%= flash[:alert] %>
  <%= flash[:notice] %>

  <%= yield %>
</body>
</html>

app/views/members/edit.html.erb
<h2>Edit Member</h2>
<%= render "layouts/member_form" %>

app/views/members/index.html.erb
<h2>All Members</h2>

<% if @members.any? %>
<ul>
  <% @members.each do |member| %>
  <li><%= link_to member.name, member_path(member) %></li>
  <% end %>
</ul>
<% else %>
<h3>There are no members to display!</h3>
<% end %>

<p><%= link_to "Create new member", new_member_path %></p>

app/views/members/new.html.erb
<h2>New Member</h2>
<%= render "layouts/member_form" %>

app/views/members/show.html.erb
<h2>Show Member</h2>

<h3><%= @member.name %></h3>
<% if @member.broadcasts.any? %>
<ul>
  <% @member.broadcasts.each do |broadcast| %>
  <li><%= link_to broadcast.description, member_broadcast_path(@member, broadcast) %></li>
</ul>
<% end %>
<% else %>
<p>No broadcasts</p>
<% end %>

app/views/users/index.html.erb
<h2>USERS</h2>